apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-baremetal-sc-syslvg
provisioner: csi-baremetal  # CSI driver name
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  storageType: SYSLVG
  fsType: xfs
