apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-baremetal-operator
  namespace: {{ .Release.Namespace }}
  labels:
    app: csi-baremetal
    app.kubernetes.io/name: csi-baremetal
spec:
  selector:
    matchLabels:
      name: {{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        name: {{ .Release.Name }}
        app: csi-baremetal
        app.kubernetes.io/name: csi-baremetal
        component: operator
        app.kubernetes.io/component: operator
        # release label used by fluentbit to make "release" folder
        release: {{ .Release.Name }}
    spec:
      serviceAccount: csi-baremetal-operator-sa
      {{- if .Values.global.registrySecret }}
      imagePullSecrets:
        - name: {{ .Values.global.registrySecret }}
      {{- end }}
      {{- if .Values.securityContext.enable }}
      securityContext:
        runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
        runAsUser: {{ .Values.securityContext.runAsUser }}
      {{- end }}
      containers:
      - command:
        - /manager
        args:
        - --enable-leader-election
        image: {{ if .Values.global.registry }}{{ .Values.global.registry }}/{{ end }}{{ .Values.operator.image.name }}:{{ default .Values.image.tag .Values.operator.image.tag }}
        name: manager
        imagePullPolicy: {{ default .Values.image.pullPolicy .Values.operator.image.pullPolicy }}
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
        volumeMounts:
        - mountPath: /crash-dump
          name: crash-dump 
      terminationGracePeriodSeconds: 10
      volumes:  
      - name: crash-dump
        emptyDir: {}

